# app.R

# Load the shiny and bslib libraries
library(shiny)
library(bslib)

# Source the authentication module
source("auth_module.R")

# Define the UI for the application
ui <- page_fluid(
  title = "TrolleyGAR 2.0",
  theme = bs_theme(version = 5, bootswatch = "cosmo"),
  
  # Conditional panel to show the login page
  # Condition now directly refers to the output generated by the login module
  # which is then exposed by the main server.
  conditionalPanel(
    condition = "!output.auth_authenticated", # This is the correct condition now
    loginUI("auth") # Call the login UI module here
  ),
  
  # Conditional panel to show the dashboard content after successful login
  conditionalPanel(
    condition = "output.auth_authenticated", # This is the correct condition now
    layout_sidebar(
      sidebar = sidebar(
        title = "Dashboard Controls",
        p("Welcome to the Dashboard!")
      ),
      card(
        card_header("Old Faithful Geyser Data"),
        card_body(
          layout_columns(
            col_widths = c(4, 8),
            sliderInput("bins",
                        "Number of bins:",
                        min = 1,
                        max = 50,
                        value = 30),
            plotOutput("distPlot")
          )
        )
      )
    )
  )
)

# Define the server logic
server <- function(input, output, session) {
  
  # Call the login server module and get its reactive authenticated status
  # The 'authenticated_status' reactive expression holds the value
  authenticated_status <- loginServer("auth")
  
  # Expose the module's authenticated status to the main output object
  # This makes 'output.auth_authenticated' available to the UI conditionalPanel
  output$auth_authenticated <- reactive({
    authenticated_status()
  })
  
  # Ensure the output is not suspended when hidden, crucial for conditionalPanel
  outputOptions(output, "auth_authenticated", suspendWhenHidden = FALSE)
  
  # --- Dashboard Server Logic (runs only when authenticated) ---
  
  # Render the plot for the Old Faithful example
  output$distPlot <- renderPlot({
    # Ensure this code only runs if the user is authenticated from the module
    req(authenticated_status()) # Use the reactive value directly here
    
    x    <- faithful[, 2]
    bins <- seq(min(x), max(x), length.out = input$bins + 1)
    
    hist(x, breaks = bins, col = 'darkgray', border = 'white')
  })
  
  # --- End Dashboard Server Logic ---
}

# Run the application
shinyApp(ui = ui, server = server)